export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  GET_POSTS: "GET_POSTS",
  GET_DETAIL_POST: "GET_DETAIL_POST",
  FETCH_POSTS_REQUEST: "FETCH_POSTS_REQUEST",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_ERROR: "FETCH_POSTS_ERROR",
  FETCH_FASHION_POSTS: "FETCH_FASHION_POSTS",
  FETCH_FASHION_POST: "FETCH_FASHION_POST",
  FETCH_FOOD_POSTS: "FETCH_FOOD_POSTS",
  FETCH_FOOD_POST: "FETCH_FOOD_POST",
};
